name: Build Android App (V2 branch)

on:
  push:
    branches: [ V2 ]
  pull_request:
    branches: [ V2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BatteryNotification-v2-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
